### ISSUE TITLE
Invalid Value Error

### ISSUE THREAD

**Issue by IndexEng** [deanmcgregor/ynab-python#8]
I have copied the get_transactions_by_account example and have included the correct api key and account/budget id. Returning an error:

```
raise ValueError("Invalid value for `flag_color`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `flag_color`, must not be `None`
```
Not sure if there is a data problem with my account?

**Comment by stenjo** [comment]
Getting the same error here too. 
`{'account_id': '604db576-*********-c2c5defe2d64',
 'account_name': 'Kredittkort',
 'amount': 98240,
 'approved': True,
 'category_id': None,
 'category_name': None,
 'cleared': 'reconciled',
 'date': '2018-12-21',
 'deleted': False,
 'flag_color': None,
 'id': 'e72efb67-****-4de1-****-4debd70e815a',
 'import_id': 'YNAB:98240:2018-12-21:1',
 'memo': 'Månedlig Betaling Kredittkort',
 'payee_id': 'c1811603-****-40a7-b7a6-272afd898162',
 'payee_name': 'Transfer : Utgiftskonto',
 'subtransactions': [],
 'transfer_account_id': '80da75df-****-4ded-9485-beabcc3e6401',
 'transfer_transaction_id': 'a8652e3a-****-40fc-8f9f-8a5e1ee61fe1'}`

This response object indicates that flag_color is a valid response. Should the API be updated likewise?
Removing the `None` checks from `transaction_detail.py` enables transactions to be listed according to the example file, but are not this file auto-generated by Swagger?

**Comment by IndexEng** [comment]
Was not able to resolve this issue myself. Found it easier just using the request library and access the YNAB API directly. Doesn't have a lot of the features of this repository but got the job done.
